local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide", "esES", false, true)

if not L then return end
if L then
L["Boat to Booty Bay"] = "Barco a Bahía del Botín"
L["Boat to Menethil Harbor"] = "Barco a Puerto de Menethil"
L["Boat to Ratchet"] = "Barco a Trinquete"
L["Boat to Theramore Isle"] = "Barco a Theramore"
L["config_boat"] = "Barco"
L["config_boat_alliance"] = "Barco de la Alianza"
L["config_boat_alliance_desc"] = "Mostrar las ubicaciones de los barcos de la Alianza."
L["config_boat_desc"] = "Mostrar las ubicaciones de los barcos."
L["config_easy_waypoints"] = "Puntos de ruta fáciles"
L["config_easy_waypoints_desc"] = "Activa la creación de puntos de ruta simplificada.\nPermite establecer un punto de ruta haciendo clic con el botón derecho y acceder a más opciones con CTRL + clic derecho."
L["config_icon_alpha"] = "Opacidad"
L["config_icon_alpha_desc"] = "Transparencia alfa de los iconos"
L["config_icon_scale"] = "Escala"
L["config_icon_scale_desc"] = "Escala de los iconos"
L["config_note"] = "Nota"
L["config_note_desc"] = "Mostrar las notas adicionales del nodo cuando esté disponible."
L["config_restore_nodes"] = "Restaurar los nodos ocultos"
L["config_restore_nodes_desc"] = "Vuelve a mostrar todos los nodos ocultos usando el menú contextual con clic derecho."
L["config_restore_nodes_print"] = "Todos los nodos ocultos han sido restaurados"
L["config_tab_general"] = "General"
L["config_tab_scale_alpha"] = "Escalar / Opacidad"
L["config_tram"] = "Tranvía Subterráneo"
L["config_tram_desc"] = "Muestra las ubicaciones del Tranvía Subterráneo en Ventormenta y Forjaz."
L["config_what_to_display"] = "¿Qué mostrar?"
L["config_what_to_display_desc"] = "Esta configuración controla qué tipo de iconos se mostrarán."
L["config_zeppelin"] = "Zepelín"
L["config_zeppelin_desc"] = "Mostrar la ubicación de Zepelines."
L["config_zeppelin_horde"] = "Zepelín de la Horda"
L["config_zeppelin_horde_desc"] = "Mostrar la ubicación de los Zepelines de la Horda."
L["Deeprun Tram to Ironforge"] = "Tranvía Subterráneo hasta Forjaz."
L["Deeprun Tram to Stormwind"] = "Tranvía Subterráneo hasta Ventormenta."
L["handler_context_menu_add_tomtom"] = "Agregar a TomTom"
L["handler_context_menu_hide_node"] = "Ocultar este nodo"
L["Zeppelin to Orgrimmar"] = "Zepelín a Orgrimmar"
L["Zeppelin to Stranglethorn Vale"] = "Zepelín a Vega de Tuercespina"

-- BCC
L["Boat to Exodar"] = "Barco a El Exodar"
L["config_plugin_desc"] = "Mostrar las ubicaciones de los portales, zepelines y barcos en el mapa del mundo y el minimapa."
L["config_portal"] = "Portal"
L["config_portal_desc"] = "Mostrar las ubicaciones de los portales."
L["Orb of translocation"] = "Orbe de translocación"
L["Portal to Darnassus"] = "Portal a Darnassus"
L["Portal to Exodar"] = "Portal a Exodar"
L["Portal to Silvermoon"] = "Portal a Lunargenta"
L["Portal to Undercity"] = "Portal a Entrañas"
L["Shattrath Portal to Isle of Quel'Danas"] = "Portal de Shattrath a la Isla de Quel'Danas"
L["Shattrath Portal to Orgrimmar"] = "Portal de Shattrath a Orgrimmar"
L["Shattrath Portal to Stormwind"] = "Portal de Shattrath a Ventormenta"
L["Speak with Zephyr"] = "Habla con Céfiro"

-- Cata
L["Portal to Dalaran Crater"] = "Portal al Cráter de Dalaran"
L["Portal to Deepholm"] = "Portal a Infralar"
L["Portal to Hyjal"] = "Portal a Hyjal"
L["Portal to Temple of Earth"] = "Portal al Templo de La Tierra"
L["Portal to the Firelands"] = "Portal a las Tierras de Fuego"
L["Portal to the Sepulcher"] = "Portal al Sepulcro"
L["Portal to Therazane's Throne"] = "Portal al Trono de Therazane"
L["Portal to Tol Barad"] = "Portal a Tol Barad"
L["Portal to Twilight Highlands"] = "Portal a las Tierras Altas Crepusculares"
L["Portal to Uldum"] = "Portal a Uldum"
L["Portal to Vashj'ir"] = "Portal a Vashj'ir"

-- MoP
L["Portal to Dalaran"] = "Portal a Dalaran"
L["Portal to Isle of Thunder"] = "Portal a Isla del Trueno"
L["Portal to Jade Forest"] = "Portal al Bosque de Jade"
L["Portal to Shado-Pan Garrison"] = "Portal al Cuartel del Shadopan"
L["Portal to Shan'ze Dao"] = "Portal a Shan'ze Dao"
L["Portal to Shattrath"] = "Portal a Shattrath"
L["Portal to Thunder Bluff"] = "Portal a Cima del Trueno"

-- WotLKC
L["Boat to Borean Tundra"] = "Barco a la Tundra Boreal"
L["Boat to Howling Fjord"] = "Barco a Fiordo Aquilonal"
L["Boat to Kamagua"] = "Barco a Kamagua"
L["Boat to Moa'Ki Harbor"] = "Barco a Puerto Moa'Ki"
L["Boat to Stormwind"] = "Barco a Ventormenta"
L["Boat to Unu'Pe"] = "Barco a Unu'Pe"
L["Dalaran Portal to Caverns of Time"] = "Portal de Dalaran a Cavernas del Tiempo"
L["handler_tooltip_data"] = "RECUPERANDO DATOS..."
L["handler_tooltip_requires_level"] = "Requiere al menos nivel"
L["handler_tooltip_requires_quest"] = "Desbloqueado con misión"
L["handler_tooltip_requires_reputation"] = "Requiere reputación con"
L["Portal to Blasted Lands"] = "Portal a Las Tierras Devastadas"
L["Portal to Orgrimmar"] = "Portal a Orgrimmar"
L["Portal to Stormwind"] = "Portal a Ventormenta"
L["Portal to the Purple Parlor"] = "Portal al Salón Púrpura"
L["Waygate to Sholazar Basin"] = "Puerta a Cuenca de Sholazar"
L["Waygate to Un'Goro Crater"] = "Puerta a Cráter de Un'Goro"
L["Zeppelin to Borean Tundra"] = "Zepelín a Tundra Boreal"
L["Zeppelin to Thunder Bluff"] = "Zepelín a Cima del Trueno"
end
