local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide", "ruRU", false, true)

if not L then return end
-- Russian translation by Кеаллах RU-Змейталак https://www.curseforge.com/members/arrogant_dreamer
if L then
L["Boat to Auberdine"] = "Корабль в Аубердин"
L["Boat to Booty Bay"] = "Корабль в Пиратскую бухту"
L["Boat to Darnassus"] = "Корабль в Дарнас"
L["Boat to Menethil Harbor"] = "Корабль в Гавань Менетилов"
L["Boat to Ratchet"] = "Корабль в Кабестан"
L["Boat to Theramore Isle"] = "Корабль на остров Терамор"
L["config_boat"] = "Корабль"
L["config_boat_alliance"] = "Корабли Альянса"
L["config_boat_alliance_desc"] = "Показать места швартовки кораблей Альянса"
L["config_boat_desc"] = "Показать места швартовки кораблей"
L["config_easy_waypoints"] = "Упрощённые путевые точки "
L["config_easy_waypoints_desc"] = "Активирует упрощённое создание путевой точки. Позволяет установить путевую точку, щёлкнув правой кнопкой мыши, и получить доступ к дополнительным параметрам, нажав CtrL+[ПКМ]."
L["config_easy_waypoints_requires"] = "Требуется"
L["config_icon_alpha"] = "Прозрачность значков"
L["config_icon_alpha_desc"] = "Изменяет прозрачность значков"
L["config_icon_scale"] = "Размер значков"
L["config_icon_scale_desc"] = "Изменяет размер значков"
L["config_note"] = "Заметка "
L["config_note_desc"] = "Показывать дополнительные заметки к значку, когда они доступны."
L["config_plugin_desc"] = "Показывает на карте мира и миникарте расположение дирижаблей и кораблей."
L["config_restore_nodes"] = "Восстановить скрытые значки"
L["config_restore_nodes_desc"] = "Восстановить все значки, которые были скрыты через контекстное меню."
L["config_restore_nodes_print"] = "Все скрытые значки были восстановлены"
L["config_tab_general"] = "Общие настройки"
L["config_tab_scale_alpha"] = "Размер / Прозрачность"
L["config_tram"] = "Подземный поезд"
L["config_tram_desc"] = "Показать Подземный поезд из Штормграда в Стальгорн."
L["config_what_to_display"] = "Что отображать?"
L["config_what_to_display_desc"] = "Эти настройки управляют типами значков, которые будут отображаться."
L["config_zeppelin"] = "Дирижабль"
L["config_zeppelin_desc"] = "Показать воздушные гавани дирижаблей."
L["config_zeppelin_horde"] = "Дирижабли Орды"
L["config_zeppelin_horde_desc"] = "Показать воздушные гавани дирижаблей Орды"
L["Deeprun Tram to Ironforge"] = "Подземный поезд в Стальгорн"
L["Deeprun Tram to Stormwind"] = "Подземный поезд в Штормград"
L["handler_context_menu_add_tomtom"] = "Добавить в TomTom"
L["handler_context_menu_hide_node"] = "Скрыть эту точку"
L["Zeppelin to Orgrimmar"] = "Дирижабль в Оргриммар"
L["Zeppelin to Stranglethorn Vale"] = "Дирижабль в Тернистую долину"
L["Zeppelin to Undercity"] = "Дирижабль в Подгород"

-- BCC
L["Boat to Exodar"] = "Корабль в Экзодар"
L["config_portal"] = "Портал"
L["config_portal_desc"] = "Показать расположение портала."
L["Orb of translocation"] = "Сфера транслокации"
L["Portal to Silvermoon"] = "Портал в Луносвет"
L["Portal to Undercity"] = "Портал в Подгород"
L["Shattrath Portal to Darnassus"] = "Шаттратский портал в Дарнас"
L["Shattrath Portal to Exodar"] = "Шаттратский портал в Экзодар"
L["Shattrath Portal to Ironforge"] = "Шаттратский портал в Стальгорн"
L["Shattrath Portal to Isle of Quel'Danas"] = "Портал из Шаттрата на остров Кель'Данас"
L["Shattrath Portal to Orgrimmar"] = "Шаттратский портал в Оргриммар"
L["Shattrath Portal to Silvermoon"] = "Шаттратский портал в Луносвет"
L["Shattrath Portal to Stormwind"] = "Шаттратский портал в Штормград"
L["Shattrath Portal to Thunder Bluff"] = "Шаттратский портал в Громовой Утес"
L["Shattrath Portal to Undercity"] = "Шаттратский портал в Подгород"

-- WotLKC
L["Boat to Borean Tundra"] = "Корабль в Борейскую тундру"
L["Boat to Howling Fjord"] = "Корабль в Ревущий фьорд"
L["Boat to Kamagua"] = "Корабль в Камагуа"
L["Boat to Moa'Ki Harbor"] = "Корабль в гавань Моа'ки"
L["Boat to Stormwind"] = "Корабль в Штормград"
L["Boat to Unu'Pe"] = "Корабль в Уну'пе"
L["Portal to Blasted Lands"] = "Портал в Выжженные земли"
L["Portal to Orgrimmar"] = "Портал в Оргриммар"
L["Portal to Stormwind"] = "Портал в Штормград"
L["Portal to the Purple Parlor"] = "Портал в Аметистовую гостиную"
L["Waygate to Sholazar Basin"] = "Связующая спираль в Низине Шолазар"
L["Waygate to Un'Goro Crater"] = "Связующая спираль в Кратере Ун'Горо"
L["Zeppelin to Borean Tundra"] = "Дирижабль в Борейскую тундру"
L["Zeppelin to Howling Fjord"] = "Дирижабль в Ревущий фьорд"
L["Zeppelin to Thunder Bluff"] = "Дирижабль в Громовой Утес"
end
