local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide", "zhCN", false, true)

if not L then return end
-- Simplified Chinese translation by swimstiger https://www.curseforge.com/members/swimstiger
if L then
L["Boat to Booty Bay"] = "去藏宝海湾的船"
L["Boat to Darnassus"] = "去达纳苏斯的船"
L["Boat to Menethil Harbor"] = "去米奈希尔港的船"
L["Boat to Ratchet"] = "去棘齿城的船"
L["Boat to Theramore Isle"] = "去塞拉摩的船"
L["config_boat"] = "船"
L["config_boat_alliance"] = "联盟船"
L["config_boat_alliance_desc"] = "显示联盟方船的位置"
L["config_boat_desc"] = "显示船的位置"
L["config_easy_waypoints"] = "简易导航点"
L["config_easy_waypoints_desc"] = "创建简易导航点。\n右键点击设置导航，CTRL + 右键更多选项。"
L["config_easy_waypoints_requires"] = "需要"
L["config_icon_alpha"] = "图标透明度"
L["config_icon_alpha_desc"] = "控制图标的透明程度"
L["config_icon_scale"] = "图标缩放"
L["config_icon_scale_desc"] = "对图标进行缩放"
L["config_note"] = "备注"
L["config_note_desc"] = "在鼠标提示中显示备注信息"
L["config_restore_nodes"] = "重置隐藏的标记"
L["config_restore_nodes_desc"] = "重新显示所有你右击并选择“隐藏”的标记"
L["config_restore_nodes_print"] = "所有隐藏图标已还原"
L["config_tab_general"] = "通用"
L["config_tab_scale_alpha"] = "缩放/透明度"
L["config_tram"] = "矿道地铁"
L["config_tram_desc"] = "显示暴风城到铁炉堡的矿道地铁入口位置"
L["config_what_to_display"] = "要显示哪些图标？"
L["config_what_to_display_desc"] = "控制地图上显示的图标种类"
L["config_zeppelin"] = "飞艇"
L["config_zeppelin_desc"] = "显示飞艇的位置"
L["config_zeppelin_horde"] = "部落飞艇"
L["config_zeppelin_horde_desc"] = "显示部落方飞艇的位置"
L["Deeprun Tram to Ironforge"] = "去铁炉堡的矿道地铁"
L["Deeprun Tram to Stormwind"] = "去暴风城的矿道地铁"
L["handler_context_menu_add_tomtom"] = "添加到TomTom"
L["handler_context_menu_hide_node"] = "隐藏图标"
L["Zeppelin to Orgrimmar"] = "去奥格瑞玛的飞艇"
L["Zeppelin to Stranglethorn Vale"] = "去荆棘谷的飞艇"
L["Zeppelin to Undercity"] = "去幽暗城的飞艇"

-- BCC
L["Boat to Exodar"] = "去埃索达的船"
L["config_plugin_desc"] = "在世界地图和小地图上显示传送门、飞艇、港口图标。"
L["config_portal"] = "传送门"
L["config_portal_desc"] = "显示传送门的位置"
L["Orb of translocation"] = "传送宝珠"
L["Portal to Darnassus"] = "通往达纳苏斯的传送门"
L["Portal to Exodar"] = "通往埃索达的传送门"
L["Portal to Silvermoon"] = "通往银月城的传送门"
L["Portal to Undercity"] = "通往幽暗城的传送门"
L["Shattrath Portal to Isle of Quel'Danas"] = "通往奎尔丹纳斯岛的沙塔斯传送门"
L["Shattrath Portal to Orgrimmar"] = "通往奥格瑞玛的沙塔斯传送门"
L["Shattrath Portal to Stormwind"] = "通往暴风城的沙塔斯传送门"
L["Speak with Zephyr"] = "和塞菲尔对话-传送"

-- Cata
L["Portal to Dalaran Crater"] = "通往达拉然巨坑的传送门"
L["Portal to Deepholm"] = "通往深岩之洲的传送门"
L["Portal to Hyjal"] = "通往海加尔的传送门"
L["Portal to Temple of Earth"] = "通往大地神殿的传送门"
L["Portal to the Firelands"] = "到火焰之地的传送门"
L["Portal to the Sepulcher"] = "通往墓地的传送门"
L["Portal to Therazane's Throne"] = "通往塞拉赞恩的王座的传送门"
L["Portal to Tol Barad"] = "通往托尔巴拉德的传送门"
L["Portal to Twilight Highlands"] = "通往暮光高地的传送门"
L["Portal to Uldum"] = "通往奥丹姆的传送门"
L["Portal to Vashj'ir"] = "通往瓦丝琪尔的传送门"

-- MoP
L["Portal to Dalaran"] = "通往达拉然（晶歌森林）的传送门"
L["Portal to Isle of Thunder"] = "通往雷神岛的传送门"
L["Portal to Jade Forest"] = "通往翡翠林的传送门"
L["Portal to Shado-Pan Garrison"] = "通往影踪卫戍营的传送门"
L["Portal to Shattrath"] = "通往沙塔斯的传送门"
L["Portal to Thunder Bluff"] = "通往雷霆崖的传送门"

-- WotLKC
L["Boat to Borean Tundra"] = "去北风冻原的船"
L["Boat to Howling Fjord"] = "去凛风峡湾的船"
L["Boat to Kamagua"] = "去卡玛古的船"
L["Boat to Moa'Ki Harbor"] = "去莫亚基港的船"
L["Boat to Stormwind"] = "去暴风城的船"
L["Boat to Unu'Pe"] = "去乌努比的船"
L["Dalaran Portal to Caverns of Time"] = "达拉然传送门：时光之穴"
L["handler_tooltip_data"] = "接收数据中..."
L["handler_tooltip_requires_level"] = "需要玩家等级"
L["handler_tooltip_requires_quest"] = "需要解锁任务"
L["handler_tooltip_requires_reputation"] = "需要声望"
L["Portal to Blasted Lands"] = "通往诅咒之地的传送门"
L["Portal to Orgrimmar"] = "通往奥格瑞玛的传送门"
L["Portal to Stormwind"] = "通往暴风城的传送门"
L["Portal to the Purple Parlor"] = "通往紫罗兰顶阁的传送门"
L["Waygate to Sholazar Basin"] = "通往休拉萨盆地的甬道之门"
L["Waygate to Un'Goro Crater"] = "通往安戈洛环形山的甬道之门"
L["Zeppelin to Borean Tundra"] = "去北风冻原的飞艇"
L["Zeppelin to Howling Fjord"] = "去凛风峡湾的飞艇"
L["Zeppelin to Thunder Bluff"] = "去雷霆崖的飞艇"
end
