local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide (Classic)", "zhTW", false, true)

if not L then return end
-- Traditional Chinese translation by ...
if L then
L["Boat to Booty Bay"] = "去藏宝海湾的船"
L["Boat to Darnassus"] = "去达纳苏斯的船"
L["Boat to Menethil Harbor"] = "去米奈希尔港的船"
L["Boat to Ratchet"] = "去棘齿城的船"
L["Boat to Theramore Isle"] = "去塞拉摩的船"
L["config_boat"] = "船"
L["config_boat_alliance"] = "联盟船"
L["config_boat_alliance_desc"] = "显示联盟方船的位置"
L["config_boat_desc"] = "显示船的位置"
L["config_easy_waypoints"] = "簡易路徑點"
L["config_easy_waypoints_desc"] = "激活創建簡化的路徑點。\n右鍵點擊設置路徑點，使用CTRL + 右鍵選取更多選項。"
L["config_easy_waypoints_requires"] = "需要"
L["config_icon_alpha"] = "图标透明度"
L["config_icon_alpha_desc"] = "控制图标的透明程度"
L["config_icon_scale"] = "图标缩放"
L["config_icon_scale_desc"] = "对图标进行缩放"
L["config_note"] = "备注"
L["config_note_desc"] = "在鼠标提示中显示备注信息"
L["config_plugin_desc"] = "在世界地图和小地图上显示船和飞艇的位置"
L["config_restore_nodes"] = "重置隐藏的标记"
L["config_restore_nodes_desc"] = "重新显示所有你右击并选择“隐藏”的标记"
L["config_restore_nodes_print"] = "已經恢復所有隱藏的節點"
L["config_tab_general"] = "一般"
L["config_tab_scale_alpha"] = "縮放 / 透明度"
L["config_tram"] = "矿道地铁"
L["config_tram_desc"] = "显示暴风城到铁炉堡的矿道地铁入口位置"
L["config_what_to_display"] = "要显示哪些图标？"
L["config_what_to_display_desc"] = "控制地图上显示的图标种类"
L["config_zeppelin"] = "飞艇"
L["config_zeppelin_desc"] = "显示飞艇的位置"
L["config_zeppelin_horde"] = "部落飞艇"
L["config_zeppelin_horde_desc"] = "显示部落方飞艇的位置"
L["Deeprun Tram to Ironforge"] = "去铁炉堡的矿道地铁"
L["Deeprun Tram to Stormwind"] = "去暴风城的矿道地铁"
L["handler_context_menu_add_tomtom"] = "添加到TomTom"
L["handler_context_menu_hide_node"] = "隱藏此節點"
L["Zeppelin to Orgrimmar"] = "去奥格瑞玛的飞艇"
L["Zeppelin to Stranglethorn Vale"] = "去荆棘谷的飞艇"
L["Zeppelin to Undercity"] = "去幽暗城的飞艇"

-- BCC
L["Boat to Exodar"] = "去埃索达的船"
L["config_portal"] = "传送门"
L["config_portal_desc"] = "显示传送门的位置"
L["Orb of translocation"] = "传送宝珠"
L["Portal to Darnassus"] = "到達納蘇斯的傳送門"
L["Portal to Exodar"] = "到艾克索達的傳送門"
L["Portal to Silvermoon"] = "通往银月城的传送门"
L["Portal to Undercity"] = "通往幽暗城的传送门"
L["Shattrath Portal to Isle of Quel'Danas"] = "通往奎尔丹纳斯岛的沙塔斯传送门"
L["Shattrath Portal to Orgrimmar"] = "通往奥格瑞玛的沙塔斯传送门"
L["Shattrath Portal to Stormwind"] = "通往暴风城的沙塔斯传送门"
L["Speak with Zephyr"] = "與賽佛對話"

-- Cata
L["Portal to Dalaran Crater"] = "到達拉然陷坑的傳送門"
L["Portal to Deepholm"] = "到地深之源的傳送門"
L["Portal to Hyjal"] = "到海加爾的傳送門"
L["Portal to Temple of Earth"] = "到大地神殿的傳送門"
L["Portal to the Sepulcher"] = "到瑟伯切爾的傳送門"
L["Portal to Therazane's Throne"] = "到瑟拉贊恩王座的傳送門"
L["Portal to Tol Barad"] = "到托巴拉德的傳送門"
L["Portal to Twilight Highlands"] = "到暮光高地的傳送門"
L["Portal to Uldum"] = "到奧丹姆的傳送門"
L["Portal to Vashj'ir"] = "到瓦許伊爾的傳送門"

-- WotLKC
L["Boat to Borean Tundra"] = "去北风冻原的船"
L["Boat to Howling Fjord"] = "去凛风峡湾的船"
L["Boat to Kamagua"] = "去卡玛古的船"
L["Boat to Moa'Ki Harbor"] = "去莫亚基港的船"
L["Boat to Stormwind"] = "去暴风城的船"
L["Boat to Unu'Pe"] = "去乌努比的船"
L["handler_tooltip_data"] = "獲取數據…"
L["handler_tooltip_requires_level"] = "需要的最低玩家等級"
L["handler_tooltip_requires_quest"] = "由任務解鎖"
L["handler_tooltip_requires_reputation"] = "需要聲望"
L["Portal to Blasted Lands"] = "通往诅咒之地的传送门"
L["Portal to Orgrimmar"] = "通往奥格瑞玛的传送门"
L["Portal to Stormwind"] = "通往暴风城的传送门"
L["Portal to the Purple Parlor"] = "通往紫罗兰顶阁的传送门"
L["Waygate to Sholazar Basin"] = "通往休拉萨盆地的甬道之门"
L["Waygate to Un'Goro Crater"] = "通往安戈洛环形山的甬道之门"
L["Zeppelin to Borean Tundra"] = "去北风冻原的飞艇"
L["Zeppelin to Howling Fjord"] = "去凛风峡湾的飞艇"
L["Zeppelin to Thunder Bluff"] = "去雷霆崖的飞艇"
end
