local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide (Classic)", "esES", false, true)

if not L then return end
if L then
L["Boat to Booty Bay"] = "Barco a Bahía del Botín"
L["Boat to Menethil Harbor"] = "Barco a Puerto de Menethil"
L["Boat to Ratchet"] = "Barco a Trinquete"
L["Boat to Theramore Isle"] = "Barco a Theramore"
L["config_boat"] = "Barco"
L["config_boat_alliance"] = "Barco de la Alianza"
L["config_boat_alliance_desc"] = "Mostrar las ubicaciones de los barcos de la Alianza."
L["config_boat_desc"] = "Mostrar las ubicaciones de los barcos."
L["config_easy_waypoints"] = "Puntos de ruta fáciles"
L["config_easy_waypoints_desc"] = "Activa la creación de puntos de ruta simplificada.\nPermite establecer un punto de ruta haciendo clic con el botón derecho y acceder a más opciones con CTRL + clic derecho."
L["config_icon_alpha"] = "Opacidad"
L["config_icon_alpha_desc"] = "Transparencia alfa de los iconos"
L["config_icon_scale"] = "Escala"
L["config_icon_scale_desc"] = "Escala de los iconos"
L["config_note"] = "Nota"
L["config_note_desc"] = "Mostrar las notas adicionales del nodo cuando esté disponible."
L["config_restore_nodes"] = "Restaurar los nodos ocultos"
L["config_restore_nodes_desc"] = "Vuelve a mostrar todos los nodos ocultos usando el menú contextual con clic derecho."
L["config_restore_nodes_print"] = "Todos los nodos ocultos han sido restaurados"
L["config_tab_general"] = "General"
L["config_tab_scale_alpha"] = "Escalar / Opacidad"
L["config_tram"] = "Tranvía Subterráneo"
L["config_tram_desc"] = "Muestra las ubicaciones del Tranvía Subterráneo en Ventormenta y Forjaz."
L["config_what_to_display"] = "¿Qué mostrar?"
L["config_what_to_display_desc"] = "Esta configuración controla qué tipo de iconos se mostrarán."
L["config_zeppelin"] = "Zepelín"
L["config_zeppelin_desc"] = "Mostrar la ubicación de Zepelines."
L["config_zeppelin_horde"] = "Zepelín de la Horda"
L["config_zeppelin_horde_desc"] = "Mostrar la ubicación de los Zepelines de la Horda."
L["Deeprun Tram to Ironforge"] = "Tranvía Subterráneo hasta Forjaz."
L["Deeprun Tram to Stormwind"] = "Tranvía Subterráneo hasta Ventormenta."
L["handler_context_menu_add_tomtom"] = "Agregar a TomTom"
L["handler_context_menu_hide_node"] = "Ocultar este nodo"
L["Zeppelin to Orgrimmar"] = "Zepelín a Orgrimmar"
L["Zeppelin to Stranglethorn Vale"] = "Zepelín a Vega de Tuercespina"

-- Classic
end
