local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide", "frFR", false, true)

if not L then return end
-- French translation by scaxfull https://www.curseforge.com/members/scaxfull
if L then
L["Boat to Booty Bay"] = "Bateau vers Baie-du-Butin"
L["Boat to Darnassus"] = "Bateau vers Darnassus"
L["Boat to Menethil Harbor"] = "Bateau vers Port de Menethil"
L["Boat to Ratchet"] = "Bateau vers Ratchet"
L["Boat to Theramore Isle"] = "Bateau vers Theramore"
L["config_boat"] = "Bateau"
L["config_boat_alliance"] = "Bateau de l'Alliance"
L["config_boat_alliance_desc"] = "Afficher locations des bateaux de l'Alliance"
L["config_boat_desc"] = "Afficher locations des bateaux"
L["config_easy_waypoints"] = "Points de passages faciles"
L["config_easy_waypoints_desc"] = "Active la création simplifiée de points de passages.\nPermet de définir un point de passage par un Clic droit et d’accéder à plus d’options par Ctrel + Clic droit."
L["config_easy_waypoints_requires"] = "Requis"
L["config_icon_alpha"] = "Transparence des icônes"
L["config_icon_alpha_desc"] = "La transparence des icônes"
L["config_icon_scale"] = "Taille des icônes"
L["config_icon_scale_desc"] = "L'échelle des icônes"
L["config_note"] = "Note"
L["config_note_desc"] = "Affiche les notes supplémentaires du nœud, lorsqu'il est disponible."
L["config_restore_nodes"] = "Réinitialiser les nœuds cachés"
L["config_restore_nodes_desc"] = "Affichez tous les nœuds que vous avez masqués manuellement en cliquant dessus avec le bouton droit de la souris et en choisissant \"masquer\""
L["config_restore_nodes_print"] = "Tous les nœuds cachés ont été restaurés"
L["config_tab_general"] = "Général"
L["config_tab_scale_alpha"] = "Échelle / Opacité"
L["config_tram"] = "Tram des Profondeurs"
L["config_tram_desc"] = "Montrez les emplacements des trams de profondeurs à Stormwind et Ironforge"
L["config_what_to_display"] = "Quoi afficher?"
L["config_what_to_display_desc"] = "Ces paramètres contrôlent le type d’icônes à afficher."
L["config_zeppelin"] = "Zeppelin"
L["config_zeppelin_desc"] = "Afficher locations des Zepplins"
L["config_zeppelin_horde"] = "Zepplin de Horde"
L["config_zeppelin_horde_desc"] = "Montrez les emplacements des Zeppelin de la Horde."
L["Deeprun Tram to Ironforge"] = "Tram des Profondeurs vers Ironforge"
L["Deeprun Tram to Stormwind"] = "Tram des Profondeurs vers Stormwind"
L["handler_context_menu_add_tomtom"] = "Ajouter à TomTom"
L["handler_context_menu_hide_node"] = "Cacher ce nœud"
L["Zeppelin to Orgrimmar"] = "Zeppelin vers Orgrimmar"
L["Zeppelin to Stranglethorn Vale"] = "Zeppelin vers Vallée de Strangleronce"
L["Zeppelin to Undercity"] = " Zeppelin vers Undercity"

-- BCC
L["Boat to Exodar"] = "Bateau vers l’Exodar"
L["config_portal"] = "Portail"
L["Orb of translocation"] = "Orbe de transposition"
L["Portal to Darnassus"] = "Portail vers Darnassus"
L["Portal to Exodar"] = "Portail vers L'Exodar"
L["Portal to Silvermoon"] = "Portail vers Lune-d'Argent"
L["Portal to Undercity"] = "Portail vers Fossoyeuse"
L["Shattrath Portal to Isle of Quel'Danas"] = "Shattrath, portail pour l'île de Quel'Danas"
L["Shattrath Portal to Orgrimmar"] = "Shattrath, portail pour Orgrimmar"
L["Shattrath Portal to Stormwind"] = "Shattrath, portail pour Hurlevent"

-- Cata
L["Portal to Dalaran Crater"] = "Portail vers le cratère de Dalaran"
L["Portal to Deepholm"] = "Portail vers le Tréfonds"
L["Portal to Hyjal"] = "Portail vers Hyjal"
L["Portal to Temple of Earth"] = "Portail vers le temple de la Terre"
L["Portal to the Firelands"] = "Portail vers les terres de Feu"
L["Portal to the Sepulcher"] = "Portail vers le Sépulcre"
L["Portal to Therazane's Throne"] = "Portail vers le Trône de Therazane"
L["Portal to Tol Barad"] = "Portail vers Tol Barad"
L["Portal to Twilight Highlands"] = "Portail vers les hautes-terres du Crépuscule"
L["Portal to Uldum"] = "Portail vers Uldum"
L["Portal to Vashj'ir"] = "Portail vers Vashj'ir"

-- MoP
L["Portal to Dalaran"] = "Portail vers Dalaran"
L["Portal to Isle of Thunder"] = "Portail vers I'île du Tonnerre"
L["Portal to Jade Forest"] = "Portail vers la forêt de Jade"
L["Portal to Shado-Pan Garrison"] = "Portail vers la garnison des Pandashan"
L["Portal to Shan'ze Dao"] = "Portail vers Dao Shan’ze"
L["Portal to Shattrath"] = "Portail vers Shattrath"
L["Portal to Thunder Bluff"] = "Portail vers les Pitons-du-Tonnerre"

-- WotLKC
L["Boat to Borean Tundra"] = "Bateau vers la Toundra Boréenne"
L["Boat to Howling Fjord"] = "Bateau vers le Fjord Hurlant"
L["Boat to Kamagua"] = "Bateau vers Kamagua"
L["Boat to Moa'Ki Harbor"] = "Bateau vers Port-Moa’ki"
L["Boat to Stormwind"] = "Bateau vers Hurlevent"
L["Boat to Unu'Pe"] = "Bateau vers Unu’pe"
L["Dalaran Portal to Caverns of Time"] = "Dalaran, portail vers les Grottes du temps"
L["handler_tooltip_data"] = "RÉCUPÉRATION DES DONNÉES..."
L["handler_tooltip_requires_level"] = "Nécessite au moins le niveau du joueur"
L["handler_tooltip_requires_quest"] = "Débloqué avec une quête"
L["Portal to Blasted Lands"] = "Portail vers les terres Foudroyées"
L["Portal to Orgrimmar"] = "Portail vers Orgrimmar"
L["Portal to Stormwind"] = "Portail vers Hurlevent"
L["Portal to the Purple Parlor"] = "Portail vers le salon Violet"
L["Zeppelin to Borean Tundra"] = "Zeppelin vers la Toundra Boréenne"
L["Zeppelin to Thunder Bluff"] = "Zeppelin vers les Pitons-du-Tonnerre"
end
