local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide", "ptBR", false, true)

if not L then return end
-- Brazilian Portuguese translation by D4MM0N1C https://www.curseforge.com/members/d4mm0n1c
if L then
L["Boat to Booty Bay"] = "Barco para Angra do Butim"
L["Boat to Darnassus"] = "Barco para Darnassus"
L["Boat to Menethil Harbor"] = "Barco para o Porto de Menethil"
L["Boat to Ratchet"] = "Barco para Vila Catraca"
L["Boat to Theramore Isle"] = "Barco para Theramore"
L["config_boat"] = "Barco"
L["config_boat_alliance"] = "Barco da Aliança"
L["config_boat_alliance_desc"] = "Mostrar a localização dos barcos da Aliança."
L["config_boat_desc"] = "Mostrar a localização dos barcos"
L["config_easy_waypoints"] = "Pontos de destino facilitados"
L["config_easy_waypoints_desc"] = "Ativa a criação de pontos de destino simplificado.\nPermite que você defina um ponto de destino simplesmente clicando com o botão direito do mouse e acessa mais opções com CTRL + clique do botão direito."
L["config_easy_waypoints_requires"] = "Requer"
L["config_icon_alpha"] = "Alfa do Ícone"
L["config_icon_alpha_desc"] = "A transparência alfa dos ícones"
L["config_icon_scale"] = "Escala do Ícone"
L["config_icon_scale_desc"] = "A escala dos ícones"
L["config_note"] = "Nota"
L["config_note_desc"] = "Mostrar notas adicionais dos pontos assim que ficarem disponíveis."
L["config_restore_nodes"] = "Restaurar os pontos ocultos"
L["config_restore_nodes_desc"] = "Mostrar todos os pontos que você ocultou manualmente clicando com o botão direito do mouse e escolhendo \"ocultar\"."
L["config_restore_nodes_print"] = "Todos os ícones foram restaurados"
L["config_tab_general"] = "Geral"
L["config_tab_scale_alpha"] = "Escala / Opacidade"
L["config_tram"] = "Metrô Correfundo"
L["config_tram_desc"] = "Mostrar as localizações do Metrô Correfundo em Ventobravo e Altaforja."
L["config_what_to_display"] = "O que mostrar?"
L["config_what_to_display_desc"] = "Estas configurações controlam que tipos de ícones serão mostrados."
L["config_zeppelin"] = "Zepelin"
L["config_zeppelin_desc"] = "Mostrar a localização dos zepelins."
L["config_zeppelin_horde"] = "Zepelin da Horda"
L["config_zeppelin_horde_desc"] = "Mostrar a localização dos Zepelins da Horda."
L["Deeprun Tram to Ironforge"] = "Metrô Correfundo para Altaforja"
L["Deeprun Tram to Stormwind"] = "Metrô Correfundo para Ventobravo"
L["handler_context_menu_add_tomtom"] = "Adicionar ao TomTom"
L["handler_context_menu_hide_node"] = "Esconder este ícone"
L["Zeppelin to Orgrimmar"] = "Zepelin para Orgrimmar"
L["Zeppelin to Stranglethorn Vale"] = "Zepelin para a Selva do Espinhaço"
L["Zeppelin to Undercity"] = "Zepelin para Cidade Baixa"

-- BCC
L["Boat to Exodar"] = "Navio para Exodar"
L["config_plugin_desc"] = "Mostra a localização de portais, zepelins e navios no Mapa-múndi e minimapa."
L["config_portal"] = "Portal"
L["config_portal_desc"] = "Mostrar as localizações dos portais."
L["Orb of translocation"] = "Orbe da Translocação"
L["Portal to Darnassus"] = "Portal para Darnassus"
L["Portal to Exodar"] = "Portal para Exodar"
L["Portal to Silvermoon"] = "Portal para Luaprata"
L["Portal to Undercity"] = "Portal para Cidade Baixa"
L["Shattrath Portal to Isle of Quel'Danas"] = "Portal de Shattrath para Ilha de Quel'Danas"
L["Shattrath Portal to Orgrimmar"] = "Portal de Shattrath para Orgrimmar"
L["Shattrath Portal to Stormwind"] = "Portal de Shattrath para Ventobravo"
L["Speak with Zephyr"] = "Fale com Zéfira"

-- Cata
L["Portal to Dalaran Crater"] = "Portal para a Cratera de Dalaran"
L["Portal to Deepholm"] = "Portal para Geodomo"
L["Portal to Hyjal"] = "Portal para Hyjal"
L["Portal to Temple of Earth"] = "Portal para Templo da Terra"
L["Portal to the Firelands"] = "Portal para as Terras do Fogo"
L["Portal to the Sepulcher"] = "Portal para o Sepulcro"
L["Portal to Therazane's Throne"] = "Portal para Trono de Therazane"
L["Portal to Tol Barad"] = "Portal para Tol Barad"
L["Portal to Twilight Highlands"] = "Portal para Planalto do Crepúsculo"
L["Portal to Uldum"] = "Portal para Uldum"
L["Portal to Vashj'ir"] = "Portal para Vashj'ir"

-- MoP
L["Portal to Dalaran"] = "Portal para Dalaran"
L["Portal to Isle of Thunder"] = "Portal para Ilha do Trovão"
L["Portal to Jade Forest"] = "Portal para Floresta de Jade"
L["Portal to Shado-Pan Garrison"] = "Portal para Guarnição Shado-Pan"
L["Portal to Shan'ze Dao"] = "Portal para Shan'ze Dao"
L["Portal to Shattrath"] = "Portal para Shattrath"
L["Portal to Thunder Bluff"] = "Portal para Penhasco do Trovão"

-- WotLKC
L["Boat to Borean Tundra"] = "Navio para Tundra Boreana"
L["Boat to Howling Fjord"] = "Navio para Fiorde Uivante"
L["Boat to Kamagua"] = "Navio para Kamagua"
L["Boat to Moa'Ki Harbor"] = "Navio para Porto Moa'ki"
L["Boat to Stormwind"] = "Navio para Ventobravo"
L["Boat to Unu'Pe"] = "Navio para Unu'Pe"
L["Dalaran Portal to Caverns of Time"] = "Portal de Dalaran para as Cavernas do Tempo"
L["handler_tooltip_data"] = "RECUPERANDO DADOS..."
L["handler_tooltip_requires_level"] = "Requer personagem com nível mínimo de"
L["handler_tooltip_requires_quest"] = "Desbloqueado com a missão"
L["handler_tooltip_requires_reputation"] = "Requer reputação com"
L["Portal to Blasted Lands"] = "Portal para a Barreira do Inferno"
L["Portal to Orgrimmar"] = "Portal para Orgrimmar"
L["Portal to Stormwind"] = "Portal para Ventobravo"
L["Portal to the Purple Parlor"] = "Portal para Salão Púrpura"
L["Zeppelin to Borean Tundra"] = "Zepelim para Tundra Boreana"
L["Zeppelin to Thunder Bluff"] = "Zepelim para Penhasco do Trovão"
end
