local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide", "esES", false, true)

if not L then return end
-- Spanish translation by  ( https://www.curseforge.com/members/ )
if L then
L["Ardenweald"] = true
L["Azsuna"] = true
L["Bastion"] = "Bastión"
L["Broken Isles"] = "Islas Abruptas"
L["Broken Isles, Stormheim"] = "Islas Abruptas, Tormenheim"
L["Broken Shore"] = "Costa Abrupta"
L["config_icon_alpha"] = "Opacidad"
L["config_icon_scale"] = "Escalar"
L["config_restore_nodes"] = "Restaurar los nodos ocultos"
L["config_restore_nodes_desc"] = "Vuelve a mostrar todos los nodos ocultos usando el menú contextual con click-derecho."
L["config_tab_general"] = "General"
L["config_tab_scale_alpha"] = "Escalar / Opacidad"
L["Dalaran"] = true
L["Darkreach"] = "Alcance Oscuro"
L["Dominance Keep"] = "Fortaleza de la Dominancia"
L["Draenor, Ashran"] = true
L["Draenor, Tanaan Jungle"] = "Draenor, Selva de Tanaan"
L["Eastern Kingdoms"] = "Reinos del Este"
L["Eastern Kingdoms, Arathi Highlands"] = "Reinos del Este, Tierras Altas de Arathi"
L["Eastern Kingdoms, Dun Morogh"] = "Reinos del Este, Dun Morogh"
L["Eastern Kingdoms, Elwynn Forest"] = "Reinos del Este, Bosque de Elwynn"
L["Eastern Kingdoms, Eversong Woods"] = "Reinos del Este, Bosque Canción Eterna"
L["Eastern Kingdoms, Grom'gol Base Camp"] = "Reinos del Este, Campamento Grom'gol"
L["Eastern Kingdoms, Hillsbrad Foothills"] = "Reinos del Este, Laderas de Trabalomas"
L["Eastern Kingdoms, Silverpine Forest"] = "Reinos del Este, Bosque de Argénteos"
L["Eastern Kingdoms, Stranglethorn Vale"] = "Reinos del Este, Vega de Tuercespina"
L["Eastern Kingdoms, Tirisfal Glades"] = "Reinos del Este, Claros de Tirisfal"
L["Eastern Kingdoms, Wetlands"] = "Reinos del Este, Los Humedales"
L["Ember Ward"] = "Distrito de las Ascuas"
L["Feeders' Thicket"] = "Matorral de los Alimentadores"
L["Halls of Atonement"] = "Salas de la Expiación"
L["handler_context_menu_add_tomtom"] = "Agregar a TomTom"
L["handler_context_menu_hide_node"] = "Ocultar este nodo"
L["handler_tooltip_requires"] = "Requiere"
L["Heartwood Grove"] = "Arboleda del Duramen"
L["Highmountain"] = "Monte Alto"
L["Kalimdor"] = true
L["Kalimdor, Azuremyst Isle"] = "Kalimdor, Isla Bruma Azur"
L["Kalimdor, Darkshore"] = "Kalimdor, Costa Oscura"
L["Kalimdor, Durotar"] = true
L["Kalimdor, Dustwallow Marsh"] = "Kalimdor, Marjal Revolcafango"
L["Kalimdor, Mulgore"] = true
L["Kalimdor, Northern Barrens"] = "Kalimdor, Los Baldíos del Norte"
L["Kalimdor, Tanaris"] = true
L["Kalimdor, Teldrassil"] = true
L["Kul Tiras"] = true
L["Kul Tiras, Tiragarde Sound"] = "Kul Tiras, Estrecho de Tiragarde"
L["Maelstrom"] = "La Vorágine"
L["Maelstrom, Deepholm"] = "La Vorágine, Infralar"
L["Maldraxxus"] = true
L["Northrend, Borean Tundra"] = "Rasganorte, Tundra Boreal"
L["Northrend, Crystalsong Forest"] = "Rasganorte, Bosque Canto de Cristal"
L["Northrend, Dragonblight"] = "Rasganorte, Cementerio de Dragones"
L["Northrend, Howling Fjord"] = "Rasganorte, Fiordo Aquilonal"
L["Northrend, Valgarde"] = "Rasganorte, Valgarde"
L["Northrend, Valiance Keep"] = "Rasganorte, Fortaleza Denuedo"
L["Northrend, Vengeance Landing"] = "Rasganorte, Campo Venganza"
L["Northrend, Warsong Hold"] = "Rasganorte, Bastión Grito de Guerra"
L["Oribos"] = true
L["Outland"] = "Terrallende"
L["Outland, Terokkar Forest"] = "Terrallende, Bosque de Terokkar"
L["Pandaria"] = true
L["Pandaria, Kun-Lai Summit"] = "Pandaria, Cima Kun-Lai"
L["Pandaria, Townlong Steppes"] = "Pandaria, Estepas de Tong Long"
L["Pridefall Hamlet"] = "Aldea de la Caída"
L["Reavendreath"] = true
L["Sanctuary of the Mad"] = "Santuario de los Locos"
L["Seat of the Primus"] = "Trono del Prelado"
L["Shadowlands"] = "Tierras Sombrías"
L["Shimmerbough"] = "Ramacentella"
L["Sinfall"] = "Salto del Pecado"
L["Stormheim"] = "Tormenheim"
L["Suramar"] = true
L["The Banewood"] = "Bosque de la Desgracia"
L["The Eternal Terrace"] = "Bancal Eterno"
L["The Maw"] = "Las Fauces"
L["Val'sharah"] = true
L["Zandalar"] = true
L["Zandalar, Zuldazar"] = true
end