local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_TravelGuide", "ruRU", false, true)

if not L then return end
-- Russian translation by  ( https://www.curseforge.com/members/ )
if L then
L["Boat to Booty Bay"] = "Корабль в Пиратскую бухту"
L["Boat to Ratchet"] = "Корабль в Кабестан"
L["Boat to Theramore"] = "Корабль на остров Терамор"
L["config_boat"] = "Корабль"
L["config_boat_alliance"] = "Корабли Альянса"
L["config_boat_alliance_desc"] = "Показать места швартовки кораблей Альянса."
L["config_boat_desc"] = "Показать места швартовки кораблей."
L["config_deeprun_tram"] = "Подземный поезд"
L["config_deeprun_tram_desc"] = "Показать Подземный поезд из Штормград в Стальгорн."
L["config_icon_alpha"] = "Прозрачность значка"
L["config_icon_alpha_desc"] = "Прозрачность значков"
L["config_icon_scale"] = "Размер значка"
L["config_icon_scale_desc"] = "Размер значков"
L["config_note"] = "Заметка"
L["config_note_desc"] = "Показать дополнительные заметки узла, когда они доступны."
L["config_tab_general"] = "Общие настройки"
L["config_tab_scale_alpha"] = "Размер / Прозрачность"
L["config_what_to_display"] = "Что отображать?"
L["config_what_to_display_desc"] = "Эти настройки определяют тип отображаемых значков."
L["config_zeppelin"] = "Дирижабль"
L["config_zeppelin_desc"] = "оказать воздушные гавани дирижаблей."
L["config_zeppelin_horde"] = "Дирижабли Орды"
L["config_zeppelin_horde_desc"] = "Показать воздушные гавани дирижаблей Орды."
L["Deeprun Tram to Ironforge"] = "Подземный поезд в Стальгорн"
L["Deeprun Tram to Stormwind"] = "Подземный поезд в Штормград"
L["handler_context_menu_add_tomtom"] = "Добавить в TomTom"
L["handler_context_menu_hide_node"] = "Скрыть эту точку"
L["handler_tooltip_requires"] = "Требуется"
L["Zeppelin to Orgrimmar"] = "Дирижабль в Оргриммар"
L["Zeppelin to Stranglethorn Vale"] = "Дирижабль в Тернистую долину"
end